<a href="https://colab.research.google.com/github/santhiravuri/generative-ai-internship/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
#sample output and target tensors

output = torch.tensor([[0.2], [0.7], [0.9]], dtype=torch.float32)
target = torch.tensor([[0.0], [1.0], [1.0]], dtype=torch.float32)

#define mse loss
loss_fn = nn.MSELoss()

#calculate loss

loss = loss_fn(output, target)

print("Output:\n", output)
print("Target:\n", target)
print("Loss:", loss.item())

Output:
 tensor([[0.2000],
        [0.7000],
        [0.9000]])
Target:
 tensor([[0.],
        [1.],
        [1.]])
Loss: 0.046666670590639114


In [ ]:
import torch
import torch.nn as nn

#samput output and target values

output=torch.tensor([[0.2], [0.7], [0.9]], dtype=torch.float32)
target = torch.tensor([[0.0], [1.0], [1.0]], dtype=torch.float32)

#define bce loss

loss_fn = nn.BCELoss()

#calculate loss

loss = loss_fn(output, target)

print("Output:\n", output)
print("Target:\n", target)
print("Loss:", loss.item())


Output:
 tensor([[0.2000],
        [0.7000],
        [0.9000]])
Target:
 tensor([[0.],
        [1.],
        [1.]])
Loss: 0.22839303314685822


In [ ]:
"""| Aspect         | MSE Loss                       | BCE Loss                    |
| -------------- | ------------------------------ | --------------------------- |
| Input Type     | Continuous                     | Binary / \[0, 1] normalized |
| Decoder Output | Linear, ReLU, Tanh             | Sigmoid                     |
| Loss Shape     | Quadratic (penalizes big diff) | Logarithmic                 |
| Output Range   | Real numbers                   | \[0, 1] probabilities       |
| Used in        | Denoising AE, VAE (reg)        | Binary AE, VAE (bin)"""

In [ ]:
#Input x ──► [Encoder] ──► Latent vector z ──► [Decoder] ──► Output x̂import torch

import torch.nn as nn
# Define the AE model (as in your code)
class AE(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(784, 128),
            nn.ReLU(),
            nn.Linear(128, 32)
        )
        self.decoder = nn.Sequential(
            nn.Linear(32, 128),
            nn.ReLU(),
            nn.Linear(128, 784),
            nn.Sigmoid()
        )

    def forward(self, x):
        z = self.encoder(x)
        return self.decoder(z)

# Create a model instance
model = AE()

# Create a sample input: a batch of 1 flattened image (values between 0 and 1)
x = torch.rand((1, 784))  # batch size = 1, each image is 784-dim (28x28)

# Pass through the model
output = model(x)

# Print the output
print("Input shape:", x.shape)
print("Output shape:", output.shape)
print("Reconstructed output (first 5 values):", output[0][:10])

Input shape: torch.Size([1, 784])
Output shape: torch.Size([1, 784])
Reconstructed output (first 5 values): tensor([0.4871, 0.4978, 0.4886, 0.4883, 0.4824, 0.4573, 0.5030, 0.4942, 0.5464,
        0.5196], grad_fn=<SliceBackward0>)
